
CREATE PROCEDURE LAB5_3B @MAPB INT,@TENPB NVARCHAR(15),
						@MATB NVARCHAR(9),@NGNC DATE
AS 
BEGIN
	IF EXISTS(SELECT * FROM PHONGBAN WHERE MAPHG= @MAPB)
		UPDATE PHONGBAN SET TENPHG = @TENPB, TRPHG = @MATB,NG_NHANCHUC= @NGNC WHERE MAPHG = @MAPB
	ELSE 
		BEGIN
			insert into PHONGBAN(MAPHG,TENPHG,TRPHG,NG_NHANCHUC)
			VALUES (@MAPB , @TENPB, @MATB, @NGNC)
			PRINT 'THANH CONG'
		END
END
EXEC LAB5_3B '8','IT','008','2020-11-24'