
CREATE PROCEDURE LAB5_3A @MAPB INT,@TENPB NVARCHAR(15),
						@MATB NVARCHAR(9),@NGNC DATE
AS 
BEGIN
	IF EXISTS(SELECT * FROM PHONGBAN WHERE MAPHG= @MAPB)
		PRINT ('THEM THAT BAI')
	ELSE 
		BEGIN
			insert into PHONGBAN(MAPHG,TENPHG,TRPHG,NG_NHANCHUC)
			VALUES (@MAPB , @TENPB, @MATB, @NGNC)
			PRINT 'THANH CONG'
		END
END
EXEC LAB5_3A '8','CNTT','008','2020-10-6'