select TENPHG , COUNT(MANV) AS 'SO LUONG NV' FROM PHONGBAN INNER JOIN NHANVIEN ON PHONGBAN.MAPHG=NHANVIEN.PHG GROUP BY PHG,TENPHG HAVING AVG(LUONG) >30000

SELECT HONV, TENLOT, TENNV , LUONG FROM NHANVIEN WHERE PHG =5 AND LUONG > (select AVG(LUONG) FROM NHANVIEN)

SELECT * FROM NHANVIEN WHERE LUONG = (SELECT MAX(LUONG) FROM NHANVIEN)

SELECT TENPHG,COUNT(MADA) AS ' SO LUONG DE AN ' FROM DEAN INNER JOIN PHONGBAN ON DEAN.PHONG = PHONGBAN.MAPHG GROUP BY TENPHG

DECLARE @P INT , @S INT, @a INT,@b INT
SET @a = 10
SET @b = 15
SET @S = @a*@b
SET @p = 2*(@a+@b)
SELECT @S AS 'CHHU VI ' , @P AS ' DIEN TICH'