CREATE TABLE NHANVIEN
(
MANV	CHAR(4) PRIMARY KEY,
HOTEN	VARCHAR(40)  NOT NULL,
SODT	VARCHAR(20)  NOT NULL,
NGVL	SMALLDATETIME  NOT NULL,
)
 CREATE TABLE SANPHAM
(
MASP	CHAR(4) PRIMARY KEY ,
TENSP	VARCHAR(40) NOT NULL,
DVT		VARCHAR(20) NOT NULL,
NUOCSX	VARCHAR(40)NOT NULL,
GIA		MONEY NOT NULL,
)

CREATE TABLE KHACHHANG
(
MAKH	CHAR(4)PRIMARY KEY,
HOTEN	VARCHAR(40) NOT NULL,
DCHI	VARCHAR(50) NOT NULL,
SODT	VARCHAR(20) NOT NULL,
NGSINH	SMALLDATETIME NOT NULL,
NGAYDK	SMALLDATETIME NOT NULL,
DOANHSO	MONEY NOT NULL,
)

CREATE TABLE HOADON
(
SOHD	INT PRIMARY KEY ,
NGAYHD	SMALLDATETIME NOT NULL,
MAKH	CHAR(4) NOT NULL,
MANV	CHAR(4) NOT NULL,
TRIGIA	MONEY NOT NULL,
CONSTRAINT FK_HOADON_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH) ON DELETE CASCADE,
CONSTRAINT FK_HOADON_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV) ON DELETE CASCADE,
)


CREATE TABLE CTHD
(
SOHD	INT NOT NULL,
MASP	CHAR(4) NOT NULL, 
SLUONG	INT NOT NULL,
PRIMARY KEY (SOHD,MASP),
constraint fk_CTHD_SoHd foreign key(SoHd) references Hoadon(SoHd) on delete cascade,
constraint fk_CTHD_MaSP foreign key(MaSP) references SanPham(MaSP) on delete cascade,
)

