
-- câu 1a cast
SELECT DEAN.TENDEAN, CAST(SUM(PHANCONG.THOIGIAN) AS decimal(5, 2)) AS [Tổng số giờ làm việc]
FROM DEAN INNER JOIN PHANCONG ON DEAN.MADA = PHANCONG.MADA GROUP BY TENDEAN

SELECT DEAN.TENDEAN, CAST(SUM(PHANCONG.THOIGIAN) AS varchar) AS [Tổng số giờ làm việc]
FROM DEAN INNER JOIN PHANCONG ON DEAN.MADA = PHANCONG.MADA GROUP BY TENDEAN

--câu 1a convert
SELECT DEAN.TENDEAN, convert(decimal(5, 2),SUM(PHANCONG.THOIGIAN)) AS [Tổng số giờ làm việc]
FROM DEAN INNER JOIN PHANCONG ON DEAN.MADA = PHANCONG.MADA GROUP BY TENDEAN


SELECT DEAN.TENDEAN, convert(varchar,SUM(PHANCONG.THOIGIAN)) AS [Tổng số giờ làm việc]
FROM DEAN INNER JOIN PHANCONG ON DEAN.MADA = PHANCONG.MADA GROUP BY TENDEAN

--cau 1b cast
SELECT PHONGBAN.MAPHG,PHONGBAN.TENPHG, CAST(AVG(NHANVIEN.LUONG) AS decimal(15, 2)) AS 'Lương trung bình'
FROM NHANVIEN INNER JOin PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG GROUP BY PHONGBAN.MAPHG,PHONGBAN.TENPHG
  


SELECT PHONGBAN.MAPHG,PHONGBAN.TENPHG, CAST(AVG(NHANVIEN.LUONG) AS varchar) AS 'Lương trung bình'
FROM NHANVIEN INNER JOin PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG GROUP BY PHONGBAN.MAPHG,PHONGBAN.TENPHG

--cau 1b convert
SELECT PHONGBAN.MAPHG,PHONGBAN.TENPHG, convert(decimal(15, 2),AVG(NHANVIEN.LUONG)) AS 'Lương trung bình'
FROM NHANVIEN INNER JOin PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG GROUP BY PHONGBAN.MAPHG,PHONGBAN.TENPHG


SELECT PHONGBAN.MAPHG,PHONGBAN.TENPHG, convert( varchar,AVG(NHANVIEN.LUONG)) AS 'Lương trung bình'
FROM NHANVIEN INNER JOin PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG GROUP BY PHONGBAN.MAPHG,PHONGBAN.TENPHG

--câu 2a
--ceiling
SELECT DEAN.TENDEAN, ceiling(SUM(PHANCONG.THOIGIAN)) AS [Tổng số giờ làm việc]
FROM DEAN INNER JOIN PHANCONG ON DEAN.MADA = PHANCONG.MADA GROUP BY TENDEAN

--floor

SELECT DEAN.TENDEAN, floor(SUM(PHANCONG.THOIGIAN)) AS [Tổng số giờ làm việc]
FROM DEAN INNER JOIN PHANCONG ON DEAN.MADA = PHANCONG.MADA GROUP BY TENDEAN
--2 CHỮ SỐ THẬP PHÂN
 SELECT DEAN.TENDEAN,round(SUM(PHANCONG.THOIGIAN),2) AS [Tổng số giờ làm việc]
FROM DEAN INNER JOIN PHANCONG ON DEAN.MADA = PHANCONG.MADA GROUP BY TENDEAN
--CÂU 2 B
	SELECT (HONV+' '+ TENNV+' '+TENLOT) AS 'NHAN VIEN CO MUC LUONG TREN LTB CUA PHG NGHIEN CUU', LUONG FROM NHANVIEN
	WHERE LUONG >( SELECT ROUND(AVG(LUONG),2)FROM NHANVIEN WHERE PHG=5)
--CAU 3 A
SELECT UPPER(HONV)AS 'HONV',LOWER(TENLOT)AS 'TENLOT',UPPER(SUBSTRING(TENNV,1,2))+SUBSTRING(TENNV,3,10)AS 'TENNV' 
FROM NHANVIEN INNER JOIN THANNHAN ON NHANVIEN.MANV=THANNHAN.MA_NVIEN GROUP BY HONV,TENLOT,TENNV
HAVING COUNT(MA_NVIEN)>2
SELECT DCHI,SUBSTRING(DCHI,CHARINDEX(' ',DCHI),CHARINDEX(',',DCHI)-3) AS 'TEN DUONG' FROM NHANVIEN


--CAU4
SELECT HONV+' '+TENNV+' '+TENLOT,NGSINH FROM NHANVIEN
WHERE YEAR(NGSINH) >= 1960 AND YEAR(NGSINH)<=1965

SELECT  *,YEAR(GETDATE())-YEAR(NGSINH) AS 'TUOI',DATENAME(WEEKDAY,NGSINH) AS WEEKDAY FROM NHANVIEN


SELECT B.TENNV AS 'TEN TRUONG PHONG',TENPHG ,TRPHG ,NG_NHANCHUC,COUNT(A.MANV) AS 'SO NHAN VIEN' FROM NHANVIEN A INNER JOIN PHONGBAN ON PHONGBAN.MAPHG=A.PHG INNER JOIN NHANVIEN B ON B.MANV=PHONGBAN.TRPHG
GROUP BY  TENPHG ,TRPHG ,NG_NHANCHUC,B.TENNV