--CAU1
CREATE TABLE BENHVIEN
(
MABV	CHAR(4) PRIMARY KEY,
TENBV	VARCHAR(40)  NOT NULL,
)
 CREATE TABLE KHOAKHAM
(
MAKHOA		CHAR(4) PRIMARY KEY ,
TENKHOA		VARCHAR(40) NOT NULL,
SOBENHNHAN	VARCHAR(20) NOT NULL,
MABV		CHAR(4)NOT NULL,
CONSTRAINT FK_KHOAKHAM_MABV FOREIGN KEY (MABV) REFERENCES BENHVIEN(MABV) ON DELETE CASCADE,

)

CREATE TABLE BENHNHAN
(
MABN		CHAR(4)PRIMARY KEY,
HOTEN		VARCHAR(40) NOT NULL,
SONGAYNV	INT NOT NULL,
NGSINH		SMALLDATETIME NOT NULL,
GIOITINH	BIT NOT NULL,
MAKHOA		CHAR(4) NOT NULL,
CONSTRAINT FK_KHOAKHAM_MAKHOA FOREIGN KEY (MAKHOA) REFERENCES KHOAKHAM(MAKHOA) ON DELETE CASCADE,
)

-- CAU 2 
SELECT MAKHOA,TENKHOA,SOBENHNHAN AS 'SO_NGUOI' FROM KHOAKHAM INNER JOIN BENHNHAN ON KHOAKHAM.MAKHOA = BENHNHAN.MAKHOA
WHERE GIOITINH='NỮ'

--CAU3
SELECT MAKHOA,SONGAYNV AS 'TIEN' FROM BENHNHAN INNER JOIN KHOAKHAM ON KHOAKHAM.MAKHOA = BENHNHAN.MAKHOA 
GROUP BY MAKHOA having TIEN = SONGAYNV*80000